### ISSUE TITLE
Now .mesh and rest of files are not saved in destinaton dercotery it rateher saves it in parrent directory

### ISSUE THREAD

**Issue by vido89** [OGRECave/blender2ogre#141]
The .mesh .scene an .material are not saved in selected directory but rather now they are saved it in 
parent dir

**Comment by vido89** [comment]
[simplescreenrecorder-2022-06-06_15.48.20.mkv.zip](https://github.com/OGRECave/blender2ogre/files/8844898/simplescreenrecorder-2022-06-06_15.48.20.mkv.zip)

**Comment by sercero** [comment]
The issue here is that when we open the Open File Dialog by default the output file is empty.

If the user does not set a filename, then Blender will save the files to the parent directory.

The solution is to set a default filename as Blender does with all its official exporters.

Will try to copy that behaviour.

**Comment by sercero** [comment]
This issue is solved by #154
