### ISSUE TITLE
Export (manual) mesh LODs

### ISSUE THREAD

**Issue by cryham** [OGRECave/blender2ogre#189]
Is it possible to export 1 .mesh with few different meshes in Blender as its LODs?
So making LODs manually in Blender, not auto generating.
E.g. I create 4 mesh variants of tree in Blender, with decimate or manual mesh reduction. Then I'd like to export it as 1 .mesh for Ogre, but specify each of 4 Blender's meshes to be LOD 1,2,3,4 geometry in that .mesh.
If not, then is this possible to do in .mesh.xml?

**Comment by sercero** [comment]
As far as I know not as you say.

But if I'm not mistaken one of the LOD options uses Blenders decimate.

However @paroj recommends using the decimation of OGRE if I remember correctly.

Generating the LODs manually would be quite a labour intensive task, because I think you have to edit the .xml manually to insert the LODs.

However, perhaps implementing what you want would not be that difficult with some naming conventions and automating the process.

**Comment by paroj** [comment]
> Is it possible to export 1 .mesh with few different meshes in Blender as its LODs?

no. that would be "manual LOD" levels in Ogre terms, i.e. separate mesh files

**Comment by cryham** [comment]
Yeah okay.
So what's the way to achieve this?
I don't think I'll have good tree LODs w/o it. Flat leaves degrade faster than round branches.

Is it possible to specify this in .mesh.xml and how?
I know it's doable from code, for OgreNext at least. Maybe just exporting few .mesh files and then some code to put them together would be better?

**Comment by paroj** [comment]
> Is it possible to specify this in .mesh.xml and how?

yes, already doing it: https://github.com/OGRECave/blender2ogre/blob/3f5d98c1515aa057c150c3984204616700f5acb7/io_ogre/ogre/mesh.py#L522

**Comment by sercero** [comment]
So a way to do this could be to add an option that says "User manual LODs" and when that option is specified we look for meshes named "base_LOD_0", "base_LOD_1", etc.

With that information, `blender2ogre` would automatically add those meshes as LODs of the base mesh.

@paroj what do you think of this?

@cryham would this solution be what you have in mind?

**Comment by cryham** [comment]
Yes, that would be good.
Would it be possible to specify distances for them too?
I'm guessing only first LOD_0 materials will be used for other meshes, that's okay.

**Comment by sercero** [comment]
> Yes, that would be good. Would it be possible to specify distances for them too? 

How it is right now, distances are equal for every LOD distance, same as the current method. If you say distance is 300 then first LOD is 300, next is 600 and so on. I don't know how you would go about encoding the distance in the object metadata

> I'm guessing only first LOD_0 materials will be used for other meshes, that's okay.

Yes. Also the LOD_n objects need to have the same material as LOD_0 applied, otherwise they will look blank (just tested that)

One isse with this method is that if you just select everything and export, you'll get errors because you selected the "LOD" meshes and the algorithm will try to find LODs for those meshes.

So, when using this you have to take the trouble to only select the base meshes when exporting.

A way to mitigate this is to make the LOD objects children of the LOD0 object.

**Comment by paroj** [comment]
removing the labels as I misread what this issue is about

**Comment by sercero** [comment]
Ups, I already modified the option.

It is not an additional option but a select between three types of LOD generation: meshtools, blender, manual.

Right now the default is Blender, @paroj do you think that perhaps the default should be "meshtools"?

> we could always check for the presence of a `base_LOD_N` mesh and skip any auto generation then. This would save us the extra option and we would only use the LOD distance from the settings. The first level must be `base_LOD_1`, as `LOD_0 == base` in ogre terms.

Doing this check would make the code more complicated in my opinion for very little gain, and most people don't even use this feature.

I'm trying to implement this in the simplest form.

**Comment by sercero** [comment]
@cryham the proposed solution is in `master`, tell us what you think.

The documentation has been updated and also an option has been replaced so you will have to delete the .pickle.

**Comment by cryham** [comment]
Okay I'll check this soon.

Just a tiny bug: the link in readme index
https://github.com/OGRECave/blender2ogre?tab=readme-ov-file#index
is bad, (doesn't send me there on github):
https://github.com/OGRECave/blender2ogre?tab=readme-ov-file#level-of-detail--lod-
it should be:
https://github.com/OGRECave/blender2ogre?tab=readme-ov-file#level-of-detail-lod

**Comment by paroj** [comment]
closing as fixed. feel free to open a new issue, if you find any bugs
