### ISSUE TITLE
create a new release

### ISSUE THREAD

**Issue by paroj** [OGRECave/blender2ogre#242]
the last one is over one year old and some people rely on tagged releases (e.g. linux distros).

I have drafted some release notes that you might want to check. Given the addition of Ogre Next materials and .scene import, I think we can bump the version to 0.9.0 (not that we follow a particular scheme here).

**Comment by sercero** [comment]
![image](https://github.com/OGRECave/blender2ogre/assets/5248597/89beb10d-c1c4-461c-8ce1-a307bca42b83)

I was thinking of creating a release closer to the release of the Elden Ring DLC since I'll be disappearing around that time 😂

Perhaps at the beginnings of june, trying to close up as much stuff as possible.

But I might be able to close most threads before that.

What do you think?

**Comment by paroj** [comment]
personally, I am a fan of [Release early, release often](https://en.wikipedia.org/wiki/Release_early,_release_often) and do a 0.9.0 release now and fix up any issues that might come up as 0.9.x

**Comment by sercero** [comment]
You are right, there are some really big changes.
